import markdown as _markdown
import re


_markdown_obj = _markdown.Markdown(extensions=[
    'markdown.extensions.tables',
    'pymdownx.magiclink',
    'pymdownx.betterem',
    'pymdownx.tilde',
    #'pymdownx.githubemoji',  # Replaced with our own
    'pymdownx.tasklist',
    'pymdownx.headeranchor',
    'pymdownx.superfences',
])

_image_re = re.compile(r'<img(?:\s+[a-zA-Z_-]+="[^"]*")+\s*/?>')
_image_attr_re = re.compile(r'([a-zA-Z_-]+)="([^"]*)"')


def gitter_to_matrix(msg):
    msg = _markdown_obj.convert(msg)
    _markdown_obj.reset()
    if msg.startswith('<p>'):
        msg = msg[3:]
    if msg.endswith('</p>'):
        msg = msg[:-4]

    # Replace emoji
    def replace_emoji(m_emoji):
        return _github_emoji_map.get(m_emoji.group(1),
                                     m_emoji.group(0))

    msg = _github_emoji_re.sub(replace_emoji, msg)

    # Go over the generated HTML (with a regex :sob:) and replace inline images
    # with links (Riot doesn't allow inline images, only attachments)
    def replace_img(m_img):
        attrs = dict((m_attr.group(1), m_attr.group(2))
                     for m_attr in _image_attr_re.finditer(m_img.group(0)))
        title = ''
        if 'title' in attrs:
            title = ' title="%s"' % attrs['title']
        alt = attrs.get('alt', '').strip()
        if alt:
            alt = alt.replace('\\"', '"')
            alt = alt.replace('<', '&lt;').replace('>', '&gt;')
            alt = ' (alt: %s)' % alt
        return '<a href="{src}"{title}><i>image{alt}</i></a>'.format(
            src=attrs.get('src', ''),
            title=title, alt=alt)

    msg = _image_re.sub(replace_img, msg)

    return msg


def matrix_to_gitter(msg):
    # Currently no fix needed, Markdown and emoji should go through fine
    return msg


_github_emoji_re = re.compile(r'''(?x)
:(
    \+1|\-1|100|1234|8ball|a|ab|abc|abcd|accept|aerial_tramway|airplane|alarm_clock|alien|ambulance|anchor|angel
    |anger|angry|anguished|ant|apple|aquarius|aries|arrow_backward|arrow_double_down|arrow_double_up
    |arrow_down|arrow_down_small|arrow_forward|arrow_heading_down|arrow_heading_up|arrow_left
    |arrow_lower_left|arrow_lower_right|arrow_right|arrow_right_hook|arrow_up|arrow_up_down
    |arrow_up_small|arrow_upper_left|arrow_upper_right|arrows_clockwise|arrows_counterclockwise|art
    |articulated_lorry|astonished|athletic_shoe|atm|b|baby|baby_bottle|baby_chick|baby_symbol|back
    |baggage_claim|balloon|ballot_box_with_check|bamboo|banana|bangbang|bank|bar_chart|barber|baseball
    |basketball|bath|bathtub|battery|bear|bee|beer|beers|beetle|beginner|bell|bento|bicyclist|bike|bikini|bird
    |birthday|black_circle|black_joker|black_large_square|black_medium_small_square|black_medium_square
    |black_nib|black_small_square|black_square_button|blossom|blowfish|blue_book|blue_car|blue_heart|blush
    |boar|boat|bomb|book|bookmark|bookmark_tabs|books|boom|boot|bouquet|bow|bowling|bowtie|boy|bread
    |bride_with_veil|bridge_at_night|briefcase|broken_heart|bug|bulb|bullettrain_front|bullettrain_side|bus
    |busstop|bust_in_silhouette|busts_in_silhouette|cactus|cake|calendar|calling|camel|camera|cancer|candy
    |capital_abcd|capricorn|car|card_index|carousel_horse|cat|cat2|cd|chart|chart_with_downwards_trend
    |chart_with_upwards_trend|checkered_flag|cherries|cherry_blossom|chestnut|chicken|children_crossing
    |chocolate_bar|christmas_tree|church|cinema|circus_tent|city_sunrise|city_sunset|cl|clap|clapper
    |clipboard|clock1|clock10|clock1030|clock11|clock1130|clock12|clock1230|clock130|clock2|clock230|clock3
    |clock330|clock4|clock430|clock5|clock530|clock6|clock630|clock7|clock730|clock8|clock830|clock9|clock930
    |closed_book|closed_lock_with_key|closed_umbrella|cloud|clubs|cn|cocktail|coffee|cold_sweat|collision
    |computer|confetti_ball|confounded|confused|congratulations|construction|construction_worker
    |convenience_store|cookie|cool|cop|copyright|corn|couple|couple_with_heart|couplekiss|cow|cow2|credit_card
    |crescent_moon|crocodile|crossed_flags|crown|cry|crying_cat_face|crystal_ball|cupid|curly_loop
    |currency_exchange|curry|custard|customs|cyclone|dancer|dancers|dango|dart|dash|date|de|deciduous_tree
    |department_store|diamond_shape_with_a_dot_inside|diamonds|disappointed|disappointed_relieved|dizzy
    |dizzy_face|do_not_litter|dog|dog2|dollar|dolls|dolphin|door|doughnut|dragon|dragon_face|dress
    |dromedary_camel|droplet|dvd|e\-mail|ear|ear_of_rice|earth_africa|earth_americas|earth_asia|egg|eggplant
    |eight|eight_pointed_black_star|eight_spoked_asterisk|electric_plug|elephant|email|end|envelope
    |envelope_with_arrow|es|euro|european_castle|european_post_office|evergreen_tree|exclamation
    |expressionless|eyeglasses|eyes|facepunch|factory|fallen_leaf|family|fast_forward|fax|fearful|feelsgood|feet
    |ferris_wheel|file_folder|finnadie|fire|fire_engine|fireworks|first_quarter_moon
    |first_quarter_moon_with_face|fish|fish_cake|fishing_pole_and_fish|fist|five|flags|flashlight|flipper
    |floppy_disk|flower_playing_cards|flushed|foggy|football|footprints|fork_and_knife|fountain|four
    |four_leaf_clover|fr|free|fried_shrimp|fries|frog|frowning|fu|fuelpump|full_moon|full_moon_with_face
    |game_die|gb|gem|gemini|ghost|gift|gift_heart|girl|globe_with_meridians|goat|goberserk|godmode|golf|grapes
    |green_apple|green_book|green_heart|grey_exclamation|grey_question|grimacing|grin|grinning|guardsman
    |guitar|gun|haircut|hamburger|hammer|hamster|hand|handbag|hankey|hash|hatched_chick|hatching_chick
    |headphones|hear_no_evil|heart|heart_decoration|heart_eyes|heart_eyes_cat|heartbeat|heartpulse|hearts
    |heavy_check_mark|heavy_division_sign|heavy_dollar_sign|heavy_exclamation_mark|heavy_minus_sign
    |heavy_multiplication_x|heavy_plus_sign|helicopter|herb|hibiscus|high_brightness|high_heel|hocho
    |honey_pot|honeybee|horse|horse_racing|hospital|hotel|hotsprings|hourglass|hourglass_flowing_sand|house
    |house_with_garden|hurtrealbad|hushed|ice_cream|icecream|id|ideograph_advantage|imp|inbox_tray
    |incoming_envelope|information_desk_person|information_source|innocent|interrobang|iphone|it
    |izakaya_lantern|jack_o_lantern|japan|japanese_castle|japanese_goblin|japanese_ogre|jeans|joy|joy_cat
    |jp|key|keycap_ten|kimono|kiss|kissing|kissing_cat|kissing_closed_eyes|kissing_heart
    |kissing_smiling_eyes|knife|koala|koko|kr|lantern|large_blue_circle|large_blue_diamond
    |large_orange_diamond|last_quarter_moon|last_quarter_moon_with_face|laughing|leaves|ledger
    |left_luggage|left_right_arrow|leftwards_arrow_with_hook|lemon|leo|leopard|libra|light_rail|link|lips
    |lipstick|lock|lock_with_ink_pen|lollipop|loop|loud_sound|loudspeaker|love_hotel|love_letter
    |low_brightness|m|mag|mag_right|mahjong|mailbox|mailbox_closed|mailbox_with_mail|mailbox_with_no_mail
    |man|man_with_gua_pi_mao|man_with_turban|mans_shoe|maple_leaf|mask|massage|meat_on_bone|mega|melon
    |memo|mens|metal|metro|microphone|microscope|milky_way|minibus|minidisc|mobile_phone_off|money_with_wings
    |moneybag|monkey|monkey_face|monorail|moon|mortar_board|mount_fuji|mountain_bicyclist|mountain_cableway
    |mountain_railway|mouse|mouse2|movie_camera|moyai|muscle|mushroom|musical_keyboard|musical_note
    |musical_score|mute|nail_care|name_badge|neckbeard|necktie|negative_squared_cross_mark|neutral_face|new
    |new_moon|new_moon_with_face|newspaper|ng|night_with_stars|nine|no_bell|no_bicycles|no_entry
    |no_entry_sign|no_good|no_mobile_phones|no_mouth|no_pedestrians|no_smoking|non\-potable_water|nose
    |notebook|notebook_with_decorative_cover|notes|nut_and_bolt|o|o2|ocean|octocat|octopus|oden|office|ok
    |ok_hand|ok_woman|older_man|older_woman|on|oncoming_automobile|oncoming_bus|oncoming_police_car
    |oncoming_taxi|one|open_book|open_file_folder|open_hands|open_mouth|ophiuchus|orange_book|outbox_tray
    |ox|package|page_facing_up|page_with_curl|pager|palm_tree|panda_face|paperclip|parking
    |part_alternation_mark|partly_sunny|passport_control|paw_prints|peach|pear|pencil|pencil2|penguin|pensive
    |performing_arts|persevere|person_frowning|person_with_blond_hair|person_with_pouting_face|phone|pig
    |pig2|pig_nose|pill|pineapple|pisces|pizza|point_down|point_left|point_right|point_up|point_up_2
    |police_car|poodle|poop|post_office|postal_horn|postbox|potable_water|pouch|poultry_leg|pound
    |pouting_cat|pray|princess|punch|purple_heart|purse|pushpin|put_litter_in_its_place|question|rabbit
    |rabbit2|racehorse|radio|radio_button|rage|rage1|rage2|rage3|rage4|railway_car|rainbow|raised_hand
    |raised_hands|raising_hand|ram|ramen|rat|recycle|red_car|red_circle|registered|relaxed|relieved|repeat
    |repeat_one|restroom|revolving_hearts|rewind|ribbon|rice|rice_ball|rice_cracker|rice_scene|ring|rocket
    |roller_coaster|rooster|rose|rotating_light|round_pushpin|rowboat|ru|rugby_football|runner|running
    |running_shirt_with_sash|sa|sagittarius|sailboat|sake|sandal|santa|satellite|satisfied|saxophone|school
    |school_satchel|scissors|scorpius|scream|scream_cat|scroll|seat|secret|see_no_evil|seedling|seven
    |shaved_ice|sheep|shell|ship|shipit|shirt|shit|shoe|shower|signal_strength|six|six_pointed_star|ski|skull
    |sleeping|sleepy|slot_machine|small_blue_diamond|small_orange_diamond|small_red_triangle
    |small_red_triangle_down|smile|smile_cat|smiley|smiley_cat|smiling_imp|smirk|smirk_cat|smoking|snail
    |snake|snowboarder|snowflake|snowman|sob|soccer|soon|sos|sound|space_invader|spades|spaghetti|sparkle
    |sparkler|sparkles|sparkling_heart|speak_no_evil|speaker|speech_balloon|speedboat|squirrel|star|star2
    |stars|station|statue_of_liberty|steam_locomotive|stew|straight_ruler|strawberry|stuck_out_tongue
    |stuck_out_tongue_closed_eyes|stuck_out_tongue_winking_eye|sun_with_face|sunflower|sunglasses|sunny
    |sunrise|sunrise_over_mountains|surfer|sushi|suspect|suspension_railway|sweat|sweat_drops|sweat_smile
    |sweet_potato|swimmer|symbols|syringe|tada|tanabata_tree|tangerine|taurus|taxi|tea|telephone
    |telephone_receiver|telescope|tennis|tent|thought_balloon|three|thumbsdown|thumbsup|ticket|tiger|tiger2
    |tired_face|tm|toilet|tokyo_tower|tomato|tongue|top|tophat|tractor|traffic_light|train|train2|tram
    |triangular_flag_on_post|triangular_ruler|trident|triumph|trolleybus|trollface|trophy|tropical_drink
    |tropical_fish|truck|trumpet|tshirt|tulip|turtle|tv|twisted_rightwards_arrows|two|two_hearts
    |two_men_holding_hands|two_women_holding_hands|u5272|u5408|u55b6|u6307|u6708|u6709|u6e80|u7121|u7533
    |u7981|u7a7a|uk|umbrella|unamused|underage|unlock|up|us|v|vertical_traffic_light|vhs|vibration_mode
    |video_camera|video_game|violin|virgo|volcano|vs|walking|waning_crescent_moon|waning_gibbous_moon
    |warning|watch|water_buffalo|watermelon|wave|wavy_dash|waxing_crescent_moon|waxing_gibbous_moon|wc|weary
    |wedding|whale|whale2|wheelchair|white_check_mark|white_circle|white_flower|white_large_square
    |white_medium_small_square|white_medium_square|white_small_square|white_square_button|wind_chime
    |wine_glass|wink|wolf|woman|womans_clothes|womans_hat|womens|worried|wrench|x|yellow_heart|yen|yum|zap
    |zero|zzz
):''')

_github_emoji_map = {
    "+1": "&#x1f44d;",
    "-1": "&#x1f44e;",
    "100": "&#x1f4af;",
    "1234": "&#x1f522;",
    "8ball": "&#x1f3b1;",
    "a": "&#x1f170;",
    "ab": "&#x1f18e;",
    "abc": "&#x1f524;",
    "abcd": "&#x1f521;",
    "accept": "&#x1f251;",
    "aerial_tramway": "&#x1f6a1;",
    "airplane": "&#x2708;",
    "alarm_clock": "&#x23f0;",
    "alien": "&#x1f47d;",
    "ambulance": "&#x1f691;",
    "anchor": "&#x2693;",
    "angel": "&#x1f47c;",
    "anger": "&#x1f4a2;",
    "angry": "&#x1f620;",
    "anguished": "&#x1f627;",
    "ant": "&#x1f41c;",
    "apple": "&#x1f34e;",
    "aquarius": "&#x2652;",
    "aries": "&#x2648;",
    "arrow_backward": "&#x25c0;",
    "arrow_double_down": "&#x23ec;",
    "arrow_double_up": "&#x23eb;",
    "arrow_down": "&#x2b07;",
    "arrow_down_small": "&#x1f53d;",
    "arrow_forward": "&#x25b6;",
    "arrow_heading_down": "&#x2935;",
    "arrow_heading_up": "&#x2934;",
    "arrow_left": "&#x2b05;",
    "arrow_lower_left": "&#x2199;",
    "arrow_lower_right": "&#x2198;",
    "arrow_right": "&#x27a1;",
    "arrow_right_hook": "&#x21aa;",
    "arrow_up": "&#x2b06;",
    "arrow_up_down": "&#x2195;",
    "arrow_up_small": "&#x1f53c;",
    "arrow_upper_left": "&#x2196;",
    "arrow_upper_right": "&#x2197;",
    "arrows_clockwise": "&#x1f503;",
    "arrows_counterclockwise": "&#x1f504;",
    "art": "&#x1f3a8;",
    "articulated_lorry": "&#x1f69b;",
    "astonished": "&#x1f632;",
    "athletic_shoe": "&#x1f45f;",
    "atm": "&#x1f3e7;",
    "b": "&#x1f171;",
    "baby": "&#x1f476;",
    "baby_bottle": "&#x1f37c;",
    "baby_chick": "&#x1f424;",
    "baby_symbol": "&#x1f6bc;",
    "back": "&#x1f519;",
    "baggage_claim": "&#x1f6c4;",
    "balloon": "&#x1f388;",
    "ballot_box_with_check": "&#x2611;",
    "bamboo": "&#x1f38d;",
    "banana": "&#x1f34c;",
    "bangbang": "&#x203c;",
    "bank": "&#x1f3e6;",
    "bar_chart": "&#x1f4ca;",
    "barber": "&#x1f488;",
    "baseball": "&#x26be;",
    "basketball": "&#x1f3c0;",
    "bath": "&#x1f6c0;",
    "bathtub": "&#x1f6c1;",
    "battery": "&#x1f50b;",
    "bear": "&#x1f43b;",
    "bee": "&#x1f41d;",
    "beer": "&#x1f37a;",
    "beers": "&#x1f37b;",
    "beetle": "&#x1f41e;",
    "beginner": "&#x1f530;",
    "bell": "&#x1f514;",
    "bento": "&#x1f371;",
    "bicyclist": "&#x1f6b4;",
    "bike": "&#x1f6b2;",
    "bikini": "&#x1f459;",
    "bird": "&#x1f426;",
    "birthday": "&#x1f382;",
    "black_circle": "&#x26ab;",
    "black_joker": "&#x1f0cf;",
    "black_large_square": "&#x2b1b;",
    "black_medium_small_square": "&#x25fe;",
    "black_medium_square": "&#x25fc;",
    "black_nib": "&#x2712;",
    "black_small_square": "&#x25aa;",
    "black_square_button": "&#x1f532;",
    "blossom": "&#x1f33c;",
    "blowfish": "&#x1f421;",
    "blue_book": "&#x1f4d8;",
    "blue_car": "&#x1f699;",
    "blue_heart": "&#x1f499;",
    "blush": "&#x1f60a;",
    "boar": "&#x1f417;",
    "boat": "&#x26f5;",
    "bomb": "&#x1f4a3;",
    "book": "&#x1f4d6;",
    "bookmark": "&#x1f516;",
    "bookmark_tabs": "&#x1f4d1;",
    "books": "&#x1f4da;",
    "boom": "&#x1f4a5;",
    "boot": "&#x1f462;",
    "bouquet": "&#x1f490;",
    "bow": "&#x1f647;",
    "bowling": "&#x1f3b3;",
    "boy": "&#x1f466;",
    "bread": "&#x1f35e;",
    "bride_with_veil": "&#x1f470;",
    "bridge_at_night": "&#x1f309;",
    "briefcase": "&#x1f4bc;",
    "broken_heart": "&#x1f494;",
    "bug": "&#x1f41b;",
    "bulb": "&#x1f4a1;",
    "bullettrain_front": "&#x1f685;",
    "bullettrain_side": "&#x1f684;",
    "bus": "&#x1f68c;",
    "busstop": "&#x1f68f;",
    "bust_in_silhouette": "&#x1f464;",
    "busts_in_silhouette": "&#x1f465;",
    "cactus": "&#x1f335;",
    "cake": "&#x1f370;",
    "calendar": "&#x1f4c6;",
    "calling": "&#x1f4f2;",
    "camel": "&#x1f42b;",
    "camera": "&#x1f4f7;",
    "cancer": "&#x264b;",
    "candy": "&#x1f36c;",
    "capital_abcd": "&#x1f520;",
    "capricorn": "&#x2651;",
    "car": "&#x1f697;",
    "card_index": "&#x1f4c7;",
    "carousel_horse": "&#x1f3a0;",
    "cat": "&#x1f431;",
    "cat2": "&#x1f408;",
    "cd": "&#x1f4bf;",
    "chart": "&#x1f4b9;",
    "chart_with_downwards_trend": "&#x1f4c9;",
    "chart_with_upwards_trend": "&#x1f4c8;",
    "checkered_flag": "&#x1f3c1;",
    "cherries": "&#x1f352;",
    "cherry_blossom": "&#x1f338;",
    "chestnut": "&#x1f330;",
    "chicken": "&#x1f414;",
    "children_crossing": "&#x1f6b8;",
    "chocolate_bar": "&#x1f36b;",
    "christmas_tree": "&#x1f384;",
    "church": "&#x26ea;",
    "cinema": "&#x1f3a6;",
    "circus_tent": "&#x1f3aa;",
    "city_sunrise": "&#x1f307;",
    "city_sunset": "&#x1f306;",
    "cl": "&#x1f191;",
    "clap": "&#x1f44f;",
    "clapper": "&#x1f3ac;",
    "clipboard": "&#x1f4cb;",
    "clock1": "&#x1f550;",
    "clock10": "&#x1f559;",
    "clock1030": "&#x1f565;",
    "clock11": "&#x1f55a;",
    "clock1130": "&#x1f566;",
    "clock12": "&#x1f55b;",
    "clock1230": "&#x1f567;",
    "clock130": "&#x1f55c;",
    "clock2": "&#x1f551;",
    "clock230": "&#x1f55d;",
    "clock3": "&#x1f552;",
    "clock330": "&#x1f55e;",
    "clock4": "&#x1f553;",
    "clock430": "&#x1f55f;",
    "clock5": "&#x1f554;",
    "clock530": "&#x1f560;",
    "clock6": "&#x1f555;",
    "clock630": "&#x1f561;",
    "clock7": "&#x1f556;",
    "clock730": "&#x1f562;",
    "clock8": "&#x1f557;",
    "clock830": "&#x1f563;",
    "clock9": "&#x1f558;",
    "clock930": "&#x1f564;",
    "closed_book": "&#x1f4d5;",
    "closed_lock_with_key": "&#x1f510;",
    "closed_umbrella": "&#x1f302;",
    "cloud": "&#x2601;",
    "clubs": "&#x2663;",
    "cn": "&#x1f1e8;&#x1f1f3;",
    "cocktail": "&#x1f378;",
    "coffee": "&#x2615;",
    "cold_sweat": "&#x1f630;",
    "collision": "&#x1f4a5;",
    "computer": "&#x1f4bb;",
    "confetti_ball": "&#x1f38a;",
    "confounded": "&#x1f616;",
    "confused": "&#x1f615;",
    "congratulations": "&#x3297;",
    "construction": "&#x1f6a7;",
    "construction_worker": "&#x1f477;",
    "convenience_store": "&#x1f3ea;",
    "cookie": "&#x1f36a;",
    "cool": "&#x1f192;",
    "cop": "&#x1f46e;",
    "copyright": "&#x00a9;",
    "corn": "&#x1f33d;",
    "couple": "&#x1f46b;",
    "couple_with_heart": "&#x1f491;",
    "couplekiss": "&#x1f48f;",
    "cow": "&#x1f42e;",
    "cow2": "&#x1f404;",
    "credit_card": "&#x1f4b3;",
    "crescent_moon": "&#x1f319;",
    "crocodile": "&#x1f40a;",
    "crossed_flags": "&#x1f38c;",
    "crown": "&#x1f451;",
    "cry": "&#x1f622;",
    "crying_cat_face": "&#x1f63f;",
    "crystal_ball": "&#x1f52e;",
    "cupid": "&#x1f498;",
    "curly_loop": "&#x27b0;",
    "currency_exchange": "&#x1f4b1;",
    "curry": "&#x1f35b;",
    "custard": "&#x1f36e;",
    "customs": "&#x1f6c3;",
    "cyclone": "&#x1f300;",
    "dancer": "&#x1f483;",
    "dancers": "&#x1f46f;",
    "dango": "&#x1f361;",
    "dart": "&#x1f3af;",
    "dash": "&#x1f4a8;",
    "date": "&#x1f4c5;",
    "de": "&#x1f1e9;&#x1f1ea;",
    "deciduous_tree": "&#x1f333;",
    "department_store": "&#x1f3ec;",
    "diamond_shape_with_a_dot_inside": "&#x1f4a0;",
    "diamonds": "&#x2666;",
    "disappointed": "&#x1f61e;",
    "disappointed_relieved": "&#x1f625;",
    "dizzy": "&#x1f4ab;",
    "dizzy_face": "&#x1f635;",
    "do_not_litter": "&#x1f6af;",
    "dog": "&#x1f436;",
    "dog2": "&#x1f415;",
    "dollar": "&#x1f4b5;",
    "dolls": "&#x1f38e;",
    "dolphin": "&#x1f42c;",
    "door": "&#x1f6aa;",
    "doughnut": "&#x1f369;",
    "dragon": "&#x1f409;",
    "dragon_face": "&#x1f432;",
    "dress": "&#x1f457;",
    "dromedary_camel": "&#x1f42a;",
    "droplet": "&#x1f4a7;",
    "dvd": "&#x1f4c0;",
    "e-mail": "&#x1f4e7;",
    "ear": "&#x1f442;",
    "ear_of_rice": "&#x1f33e;",
    "earth_africa": "&#x1f30d;",
    "earth_americas": "&#x1f30e;",
    "earth_asia": "&#x1f30f;",
    "egg": "&#x1f373;",
    "eggplant": "&#x1f346;",
    "eight": "&#x0038;&#x20e3;",
    "eight_pointed_black_star": "&#x2734;",
    "eight_spoked_asterisk": "&#x2733;",
    "electric_plug": "&#x1f50c;",
    "elephant": "&#x1f418;",
    "email": "&#x2709;",
    "end": "&#x1f51a;",
    "envelope": "&#x2709;",
    "envelope_with_arrow": "&#x1f4e9;",
    "es": "&#x1f1ea;&#x1f1f8;",
    "euro": "&#x1f4b6;",
    "european_castle": "&#x1f3f0;",
    "european_post_office": "&#x1f3e4;",
    "evergreen_tree": "&#x1f332;",
    "exclamation": "&#x2757;",
    "expressionless": "&#x1f611;",
    "eyeglasses": "&#x1f453;",
    "eyes": "&#x1f440;",
    "facepunch": "&#x1f44a;",
    "factory": "&#x1f3ed;",
    "fallen_leaf": "&#x1f342;",
    "family": "&#x1f46a;",
    "fast_forward": "&#x23e9;",
    "fax": "&#x1f4e0;",
    "fearful": "&#x1f628;",
    "feet": "&#x1f43e;",
    "ferris_wheel": "&#x1f3a1;",
    "file_folder": "&#x1f4c1;",
    "fire": "&#x1f525;",
    "fire_engine": "&#x1f692;",
    "fireworks": "&#x1f386;",
    "first_quarter_moon": "&#x1f313;",
    "first_quarter_moon_with_face": "&#x1f31b;",
    "fish": "&#x1f41f;",
    "fish_cake": "&#x1f365;",
    "fishing_pole_and_fish": "&#x1f3a3;",
    "fist": "&#x270a;",
    "five": "&#x0035;&#x20e3;",
    "flags": "&#x1f38f;",
    "flashlight": "&#x1f526;",
    "flipper": "&#x1f42c;",
    "floppy_disk": "&#x1f4be;",
    "flower_playing_cards": "&#x1f3b4;",
    "flushed": "&#x1f633;",
    "foggy": "&#x1f301;",
    "football": "&#x1f3c8;",
    "footprints": "&#x1f463;",
    "fork_and_knife": "&#x1f374;",
    "fountain": "&#x26f2;",
    "four": "&#x0034;&#x20e3;",
    "four_leaf_clover": "&#x1f340;",
    "fr": "&#x1f1eb;&#x1f1f7;",
    "free": "&#x1f193;",
    "fried_shrimp": "&#x1f364;",
    "fries": "&#x1f35f;",
    "frog": "&#x1f438;",
    "frowning": "&#x1f626;",
    "fuelpump": "&#x26fd;",
    "full_moon": "&#x1f315;",
    "full_moon_with_face": "&#x1f31d;",
    "game_die": "&#x1f3b2;",
    "gb": "&#x1f1ec;&#x1f1e7;",
    "gem": "&#x1f48e;",
    "gemini": "&#x264a;",
    "ghost": "&#x1f47b;",
    "gift": "&#x1f381;",
    "gift_heart": "&#x1f49d;",
    "girl": "&#x1f467;",
    "globe_with_meridians": "&#x1f310;",
    "goat": "&#x1f410;",
    "golf": "&#x26f3;",
    "grapes": "&#x1f347;",
    "green_apple": "&#x1f34f;",
    "green_book": "&#x1f4d7;",
    "green_heart": "&#x1f49a;",
    "grey_exclamation": "&#x2755;",
    "grey_question": "&#x2754;",
    "grimacing": "&#x1f62c;",
    "grin": "&#x1f601;",
    "grinning": "&#x1f600;",
    "guardsman": "&#x1f482;",
    "guitar": "&#x1f3b8;",
    "gun": "&#x1f52b;",
    "haircut": "&#x1f487;",
    "hamburger": "&#x1f354;",
    "hammer": "&#x1f528;",
    "hamster": "&#x1f439;",
    "hand": "&#x270b;",
    "handbag": "&#x1f45c;",
    "hankey": "&#x1f4a9;",
    "hash": "&#x0023;&#x20e3;",
    "hatched_chick": "&#x1f425;",
    "hatching_chick": "&#x1f423;",
    "headphones": "&#x1f3a7;",
    "hear_no_evil": "&#x1f649;",
    "heart": "&#x2764;",
    "heart_decoration": "&#x1f49f;",
    "heart_eyes": "&#x1f60d;",
    "heart_eyes_cat": "&#x1f63b;",
    "heartbeat": "&#x1f493;",
    "heartpulse": "&#x1f497;",
    "hearts": "&#x2665;",
    "heavy_check_mark": "&#x2714;",
    "heavy_division_sign": "&#x2797;",
    "heavy_dollar_sign": "&#x1f4b2;",
    "heavy_exclamation_mark": "&#x2757;",
    "heavy_minus_sign": "&#x2796;",
    "heavy_multiplication_x": "&#x2716;",
    "heavy_plus_sign": "&#x2795;",
    "helicopter": "&#x1f681;",
    "herb": "&#x1f33f;",
    "hibiscus": "&#x1f33a;",
    "high_brightness": "&#x1f506;",
    "high_heel": "&#x1f460;",
    "hocho": "&#x1f52a;",
    "honey_pot": "&#x1f36f;",
    "honeybee": "&#x1f41d;",
    "horse": "&#x1f434;",
    "horse_racing": "&#x1f3c7;",
    "hospital": "&#x1f3e5;",
    "hotel": "&#x1f3e8;",
    "hotsprings": "&#x2668;",
    "hourglass": "&#x231b;",
    "hourglass_flowing_sand": "&#x23f3;",
    "house": "&#x1f3e0;",
    "house_with_garden": "&#x1f3e1;",
    "hushed": "&#x1f62f;",
    "ice_cream": "&#x1f368;",
    "icecream": "&#x1f366;",
    "id": "&#x1f194;",
    "ideograph_advantage": "&#x1f250;",
    "imp": "&#x1f47f;",
    "inbox_tray": "&#x1f4e5;",
    "incoming_envelope": "&#x1f4e8;",
    "information_desk_person": "&#x1f481;",
    "information_source": "&#x2139;",
    "innocent": "&#x1f607;",
    "interrobang": "&#x2049;",
    "iphone": "&#x1f4f1;",
    "it": "&#x1f1ee;&#x1f1f9;",
    "izakaya_lantern": "&#x1f3ee;",
    "jack_o_lantern": "&#x1f383;",
    "japan": "&#x1f5fe;",
    "japanese_castle": "&#x1f3ef;",
    "japanese_goblin": "&#x1f47a;",
    "japanese_ogre": "&#x1f479;",
    "jeans": "&#x1f456;",
    "joy": "&#x1f602;",
    "joy_cat": "&#x1f639;",
    "jp": "&#x1f1ef;&#x1f1f5;",
    "key": "&#x1f511;",
    "keycap_ten": "&#x1f51f;",
    "kimono": "&#x1f458;",
    "kiss": "&#x1f48b;",
    "kissing": "&#x1f617;",
    "kissing_cat": "&#x1f63d;",
    "kissing_closed_eyes": "&#x1f61a;",
    "kissing_heart": "&#x1f618;",
    "kissing_smiling_eyes": "&#x1f619;",
    "knife": "&#x1f52a;",
    "koala": "&#x1f428;",
    "koko": "&#x1f201;",
    "kr": "&#x1f1f0;&#x1f1f7;",
    "lantern": "&#x1f3ee;",
    "large_blue_circle": "&#x1f535;",
    "large_blue_diamond": "&#x1f537;",
    "large_orange_diamond": "&#x1f536;",
    "last_quarter_moon": "&#x1f317;",
    "last_quarter_moon_with_face": "&#x1f31c;",
    "laughing": "&#x1f606;",
    "leaves": "&#x1f343;",
    "ledger": "&#x1f4d2;",
    "left_luggage": "&#x1f6c5;",
    "left_right_arrow": "&#x2194;",
    "leftwards_arrow_with_hook": "&#x21a9;",
    "lemon": "&#x1f34b;",
    "leo": "&#x264c;",
    "leopard": "&#x1f406;",
    "libra": "&#x264e;",
    "light_rail": "&#x1f688;",
    "link": "&#x1f517;",
    "lips": "&#x1f444;",
    "lipstick": "&#x1f484;",
    "lock": "&#x1f512;",
    "lock_with_ink_pen": "&#x1f50f;",
    "lollipop": "&#x1f36d;",
    "loop": "&#x27bf;",
    "loud_sound": "&#x1f50a;",
    "loudspeaker": "&#x1f4e2;",
    "love_hotel": "&#x1f3e9;",
    "love_letter": "&#x1f48c;",
    "low_brightness": "&#x1f505;",
    "m": "&#x24c2;",
    "mag": "&#x1f50d;",
    "mag_right": "&#x1f50e;",
    "mahjong": "&#x1f004;",
    "mailbox": "&#x1f4eb;",
    "mailbox_closed": "&#x1f4ea;",
    "mailbox_with_mail": "&#x1f4ec;",
    "mailbox_with_no_mail": "&#x1f4ed;",
    "man": "&#x1f468;",
    "man_with_gua_pi_mao": "&#x1f472;",
    "man_with_turban": "&#x1f473;",
    "mans_shoe": "&#x1f45e;",
    "maple_leaf": "&#x1f341;",
    "mask": "&#x1f637;",
    "massage": "&#x1f486;",
    "meat_on_bone": "&#x1f356;",
    "mega": "&#x1f4e3;",
    "melon": "&#x1f348;",
    "memo": "&#x1f4dd;",
    "mens": "&#x1f6b9;",
    "metro": "&#x1f687;",
    "microphone": "&#x1f3a4;",
    "microscope": "&#x1f52c;",
    "milky_way": "&#x1f30c;",
    "minibus": "&#x1f690;",
    "minidisc": "&#x1f4bd;",
    "mobile_phone_off": "&#x1f4f4;",
    "money_with_wings": "&#x1f4b8;",
    "moneybag": "&#x1f4b0;",
    "monkey": "&#x1f412;",
    "monkey_face": "&#x1f435;",
    "monorail": "&#x1f69d;",
    "moon": "&#x1f314;",
    "mortar_board": "&#x1f393;",
    "mount_fuji": "&#x1f5fb;",
    "mountain_bicyclist": "&#x1f6b5;",
    "mountain_cableway": "&#x1f6a0;",
    "mountain_railway": "&#x1f69e;",
    "mouse": "&#x1f42d;",
    "mouse2": "&#x1f401;",
    "movie_camera": "&#x1f3a5;",
    "moyai": "&#x1f5ff;",
    "muscle": "&#x1f4aa;",
    "mushroom": "&#x1f344;",
    "musical_keyboard": "&#x1f3b9;",
    "musical_note": "&#x1f3b5;",
    "musical_score": "&#x1f3bc;",
    "mute": "&#x1f507;",
    "nail_care": "&#x1f485;",
    "name_badge": "&#x1f4db;",
    "necktie": "&#x1f454;",
    "negative_squared_cross_mark": "&#x274e;",
    "neutral_face": "&#x1f610;",
    "new": "&#x1f195;",
    "new_moon": "&#x1f311;",
    "new_moon_with_face": "&#x1f31a;",
    "newspaper": "&#x1f4f0;",
    "ng": "&#x1f196;",
    "night_with_stars": "&#x1f303;",
    "nine": "&#x0039;&#x20e3;",
    "no_bell": "&#x1f515;",
    "no_bicycles": "&#x1f6b3;",
    "no_entry": "&#x26d4;",
    "no_entry_sign": "&#x1f6ab;",
    "no_good": "&#x1f645;",
    "no_mobile_phones": "&#x1f4f5;",
    "no_mouth": "&#x1f636;",
    "no_pedestrians": "&#x1f6b7;",
    "no_smoking": "&#x1f6ad;",
    "non-potable_water": "&#x1f6b1;",
    "nose": "&#x1f443;",
    "notebook": "&#x1f4d3;",
    "notebook_with_decorative_cover": "&#x1f4d4;",
    "notes": "&#x1f3b6;",
    "nut_and_bolt": "&#x1f529;",
    "o": "&#x2b55;",
    "o2": "&#x1f17e;",
    "ocean": "&#x1f30a;",
    "octopus": "&#x1f419;",
    "oden": "&#x1f362;",
    "office": "&#x1f3e2;",
    "ok": "&#x1f197;",
    "ok_hand": "&#x1f44c;",
    "ok_woman": "&#x1f646;",
    "older_man": "&#x1f474;",
    "older_woman": "&#x1f475;",
    "on": "&#x1f51b;",
    "oncoming_automobile": "&#x1f698;",
    "oncoming_bus": "&#x1f68d;",
    "oncoming_police_car": "&#x1f694;",
    "oncoming_taxi": "&#x1f696;",
    "one": "&#x0031;&#x20e3;",
    "open_book": "&#x1f4d6;",
    "open_file_folder": "&#x1f4c2;",
    "open_hands": "&#x1f450;",
    "open_mouth": "&#x1f62e;",
    "ophiuchus": "&#x26ce;",
    "orange_book": "&#x1f4d9;",
    "outbox_tray": "&#x1f4e4;",
    "ox": "&#x1f402;",
    "package": "&#x1f4e6;",
    "page_facing_up": "&#x1f4c4;",
    "page_with_curl": "&#x1f4c3;",
    "pager": "&#x1f4df;",
    "palm_tree": "&#x1f334;",
    "panda_face": "&#x1f43c;",
    "paperclip": "&#x1f4ce;",
    "parking": "&#x1f17f;",
    "part_alternation_mark": "&#x303d;",
    "partly_sunny": "&#x26c5;",
    "passport_control": "&#x1f6c2;",
    "paw_prints": "&#x1f43e;",
    "peach": "&#x1f351;",
    "pear": "&#x1f350;",
    "pencil": "&#x1f4dd;",
    "pencil2": "&#x270f;",
    "penguin": "&#x1f427;",
    "pensive": "&#x1f614;",
    "performing_arts": "&#x1f3ad;",
    "persevere": "&#x1f623;",
    "person_frowning": "&#x1f64d;",
    "person_with_blond_hair": "&#x1f471;",
    "person_with_pouting_face": "&#x1f64e;",
    "phone": "&#x260e;",
    "pig": "&#x1f437;",
    "pig2": "&#x1f416;",
    "pig_nose": "&#x1f43d;",
    "pill": "&#x1f48a;",
    "pineapple": "&#x1f34d;",
    "pisces": "&#x2653;",
    "pizza": "&#x1f355;",
    "point_down": "&#x1f447;",
    "point_left": "&#x1f448;",
    "point_right": "&#x1f449;",
    "point_up": "&#x261d;",
    "point_up_2": "&#x1f446;",
    "police_car": "&#x1f693;",
    "poodle": "&#x1f429;",
    "poop": "&#x1f4a9;",
    "post_office": "&#x1f3e3;",
    "postal_horn": "&#x1f4ef;",
    "postbox": "&#x1f4ee;",
    "potable_water": "&#x1f6b0;",
    "pouch": "&#x1f45d;",
    "poultry_leg": "&#x1f357;",
    "pound": "&#x1f4b7;",
    "pouting_cat": "&#x1f63e;",
    "pray": "&#x1f64f;",
    "princess": "&#x1f478;",
    "punch": "&#x1f44a;",
    "purple_heart": "&#x1f49c;",
    "purse": "&#x1f45b;",
    "pushpin": "&#x1f4cc;",
    "put_litter_in_its_place": "&#x1f6ae;",
    "question": "&#x2753;",
    "rabbit": "&#x1f430;",
    "rabbit2": "&#x1f407;",
    "racehorse": "&#x1f40e;",
    "radio": "&#x1f4fb;",
    "radio_button": "&#x1f518;",
    "rage": "&#x1f621;",
    "railway_car": "&#x1f683;",
    "rainbow": "&#x1f308;",
    "raised_hand": "&#x270b;",
    "raised_hands": "&#x1f64c;",
    "raising_hand": "&#x1f64b;",
    "ram": "&#x1f40f;",
    "ramen": "&#x1f35c;",
    "rat": "&#x1f400;",
    "recycle": "&#x267b;",
    "red_car": "&#x1f697;",
    "red_circle": "&#x1f534;",
    "registered": "&#x00ae;",
    "relaxed": "&#x263a;",
    "relieved": "&#x1f60c;",
    "repeat": "&#x1f501;",
    "repeat_one": "&#x1f502;",
    "restroom": "&#x1f6bb;",
    "revolving_hearts": "&#x1f49e;",
    "rewind": "&#x23ea;",
    "ribbon": "&#x1f380;",
    "rice": "&#x1f35a;",
    "rice_ball": "&#x1f359;",
    "rice_cracker": "&#x1f358;",
    "rice_scene": "&#x1f391;",
    "ring": "&#x1f48d;",
    "rocket": "&#x1f680;",
    "roller_coaster": "&#x1f3a2;",
    "rooster": "&#x1f413;",
    "rose": "&#x1f339;",
    "rotating_light": "&#x1f6a8;",
    "round_pushpin": "&#x1f4cd;",
    "rowboat": "&#x1f6a3;",
    "ru": "&#x1f1f7;&#x1f1fa;",
    "rugby_football": "&#x1f3c9;",
    "runner": "&#x1f3c3;",
    "running": "&#x1f3c3;",
    "running_shirt_with_sash": "&#x1f3bd;",
    "sa": "&#x1f202;",
    "sagittarius": "&#x2650;",
    "sailboat": "&#x26f5;",
    "sake": "&#x1f376;",
    "sandal": "&#x1f461;",
    "santa": "&#x1f385;",
    "satellite": "&#x1f4e1;",
    "satisfied": "&#x1f606;",
    "saxophone": "&#x1f3b7;",
    "school": "&#x1f3eb;",
    "school_satchel": "&#x1f392;",
    "scissors": "&#x2702;",
    "scorpius": "&#x264f;",
    "scream": "&#x1f631;",
    "scream_cat": "&#x1f640;",
    "scroll": "&#x1f4dc;",
    "seat": "&#x1f4ba;",
    "secret": "&#x3299;",
    "see_no_evil": "&#x1f648;",
    "seedling": "&#x1f331;",
    "seven": "&#x0037;&#x20e3;",
    "shaved_ice": "&#x1f367;",
    "sheep": "&#x1f411;",
    "shell": "&#x1f41a;",
    "ship": "&#x1f6a2;",
    "shirt": "&#x1f455;",
    "shit": "&#x1f4a9;",
    "shoe": "&#x1f45e;",
    "shower": "&#x1f6bf;",
    "signal_strength": "&#x1f4f6;",
    "six": "&#x0036;&#x20e3;",
    "six_pointed_star": "&#x1f52f;",
    "ski": "&#x1f3bf;",
    "skull": "&#x1f480;",
    "sleeping": "&#x1f634;",
    "sleepy": "&#x1f62a;",
    "slot_machine": "&#x1f3b0;",
    "small_blue_diamond": "&#x1f539;",
    "small_orange_diamond": "&#x1f538;",
    "small_red_triangle": "&#x1f53a;",
    "small_red_triangle_down": "&#x1f53b;",
    "smile": "&#x1f604;",
    "smile_cat": "&#x1f638;",
    "smiley": "&#x1f603;",
    "smiley_cat": "&#x1f63a;",
    "smiling_imp": "&#x1f608;",
    "smirk": "&#x1f60f;",
    "smirk_cat": "&#x1f63c;",
    "smoking": "&#x1f6ac;",
    "snail": "&#x1f40c;",
    "snake": "&#x1f40d;",
    "snowboarder": "&#x1f3c2;",
    "snowflake": "&#x2744;",
    "snowman": "&#x26c4;",
    "sob": "&#x1f62d;",
    "soccer": "&#x26bd;",
    "soon": "&#x1f51c;",
    "sos": "&#x1f198;",
    "sound": "&#x1f509;",
    "space_invader": "&#x1f47e;",
    "spades": "&#x2660;",
    "spaghetti": "&#x1f35d;",
    "sparkle": "&#x2747;",
    "sparkler": "&#x1f387;",
    "sparkles": "&#x2728;",
    "sparkling_heart": "&#x1f496;",
    "speak_no_evil": "&#x1f64a;",
    "speaker": "&#x1f508;",
    "speech_balloon": "&#x1f4ac;",
    "speedboat": "&#x1f6a4;",
    "star": "&#x2b50;",
    "star2": "&#x1f31f;",
    "stars": "&#x1f320;",
    "station": "&#x1f689;",
    "statue_of_liberty": "&#x1f5fd;",
    "steam_locomotive": "&#x1f682;",
    "stew": "&#x1f372;",
    "straight_ruler": "&#x1f4cf;",
    "strawberry": "&#x1f353;",
    "stuck_out_tongue": "&#x1f61b;",
    "stuck_out_tongue_closed_eyes": "&#x1f61d;",
    "stuck_out_tongue_winking_eye": "&#x1f61c;",
    "sun_with_face": "&#x1f31e;",
    "sunflower": "&#x1f33b;",
    "sunglasses": "&#x1f60e;",
    "sunny": "&#x2600;",
    "sunrise": "&#x1f305;",
    "sunrise_over_mountains": "&#x1f304;",
    "surfer": "&#x1f3c4;",
    "sushi": "&#x1f363;",
    "suspension_railway": "&#x1f69f;",
    "sweat": "&#x1f613;",
    "sweat_drops": "&#x1f4a6;",
    "sweat_smile": "&#x1f605;",
    "sweet_potato": "&#x1f360;",
    "swimmer": "&#x1f3ca;",
    "symbols": "&#x1f523;",
    "syringe": "&#x1f489;",
    "tada": "&#x1f389;",
    "tanabata_tree": "&#x1f38b;",
    "tangerine": "&#x1f34a;",
    "taurus": "&#x2649;",
    "taxi": "&#x1f695;",
    "tea": "&#x1f375;",
    "telephone": "&#x260e;",
    "telephone_receiver": "&#x1f4de;",
    "telescope": "&#x1f52d;",
    "tennis": "&#x1f3be;",
    "tent": "&#x26fa;",
    "thought_balloon": "&#x1f4ad;",
    "three": "&#x0033;&#x20e3;",
    "thumbsdown": "&#x1f44e;",
    "thumbsup": "&#x1f44d;",
    "ticket": "&#x1f3ab;",
    "tiger": "&#x1f42f;",
    "tiger2": "&#x1f405;",
    "tired_face": "&#x1f62b;",
    "tm": "&#x2122;",
    "toilet": "&#x1f6bd;",
    "tokyo_tower": "&#x1f5fc;",
    "tomato": "&#x1f345;",
    "tongue": "&#x1f445;",
    "top": "&#x1f51d;",
    "tophat": "&#x1f3a9;",
    "tractor": "&#x1f69c;",
    "traffic_light": "&#x1f6a5;",
    "train": "&#x1f68b;",
    "train2": "&#x1f686;",
    "tram": "&#x1f68a;",
    "triangular_flag_on_post": "&#x1f6a9;",
    "triangular_ruler": "&#x1f4d0;",
    "trident": "&#x1f531;",
    "triumph": "&#x1f624;",
    "trolleybus": "&#x1f68e;",
    "trophy": "&#x1f3c6;",
    "tropical_drink": "&#x1f379;",
    "tropical_fish": "&#x1f420;",
    "truck": "&#x1f69a;",
    "trumpet": "&#x1f3ba;",
    "tshirt": "&#x1f455;",
    "tulip": "&#x1f337;",
    "turtle": "&#x1f422;",
    "tv": "&#x1f4fa;",
    "twisted_rightwards_arrows": "&#x1f500;",
    "two": "&#x0032;&#x20e3;",
    "two_hearts": "&#x1f495;",
    "two_men_holding_hands": "&#x1f46c;",
    "two_women_holding_hands": "&#x1f46d;",
    "u5272": "&#x1f239;",
    "u5408": "&#x1f234;",
    "u55b6": "&#x1f23a;",
    "u6307": "&#x1f22f;",
    "u6708": "&#x1f237;",
    "u6709": "&#x1f236;",
    "u6e80": "&#x1f235;",
    "u7121": "&#x1f21a;",
    "u7533": "&#x1f238;",
    "u7981": "&#x1f232;",
    "u7a7a": "&#x1f233;",
    "uk": "&#x1f1ec;&#x1f1e7;",
    "umbrella": "&#x2614;",
    "unamused": "&#x1f612;",
    "underage": "&#x1f51e;",
    "unlock": "&#x1f513;",
    "up": "&#x1f199;",
    "us": "&#x1f1fa;&#x1f1f8;",
    "v": "&#x270c;",
    "vertical_traffic_light": "&#x1f6a6;",
    "vhs": "&#x1f4fc;",
    "vibration_mode": "&#x1f4f3;",
    "video_camera": "&#x1f4f9;",
    "video_game": "&#x1f3ae;",
    "violin": "&#x1f3bb;",
    "virgo": "&#x264d;",
    "volcano": "&#x1f30b;",
    "vs": "&#x1f19a;",
    "walking": "&#x1f6b6;",
    "waning_crescent_moon": "&#x1f318;",
    "waning_gibbous_moon": "&#x1f316;",
    "warning": "&#x26a0;",
    "watch": "&#x231a;",
    "water_buffalo": "&#x1f403;",
    "watermelon": "&#x1f349;",
    "wave": "&#x1f44b;",
    "wavy_dash": "&#x3030;",
    "waxing_crescent_moon": "&#x1f312;",
    "waxing_gibbous_moon": "&#x1f314;",
    "wc": "&#x1f6be;",
    "weary": "&#x1f629;",
    "wedding": "&#x1f492;",
    "whale": "&#x1f433;",
    "whale2": "&#x1f40b;",
    "wheelchair": "&#x267f;",
    "white_check_mark": "&#x2705;",
    "white_circle": "&#x26aa;",
    "white_flower": "&#x1f4ae;",
    "white_large_square": "&#x2b1c;",
    "white_medium_small_square": "&#x25fd;",
    "white_medium_square": "&#x25fb;",
    "white_small_square": "&#x25ab;",
    "white_square_button": "&#x1f533;",
    "wind_chime": "&#x1f390;",
    "wine_glass": "&#x1f377;",
    "wink": "&#x1f609;",
    "wolf": "&#x1f43a;",
    "woman": "&#x1f469;",
    "womans_clothes": "&#x1f45a;",
    "womans_hat": "&#x1f452;",
    "womens": "&#x1f6ba;",
    "worried": "&#x1f61f;",
    "wrench": "&#x1f527;",
    "x": "&#x274c;",
    "yellow_heart": "&#x1f49b;",
    "yen": "&#x1f4b4;",
    "yum": "&#x1f60b;",
    "zap": "&#x26a1;",
    "zero": "&#x0030;&#x20e3;",
    "zzz": "&#x1f4a4;",

    # Recognized by GitHub but not valid Unicode emoji
    #"bowtie":
    #"feelsgood":
    #"finnadie":
    #"fu":
    #"goberserk":
    #"godmode":
    #"hurtrealbad":
    #"metal":
    #"neckbeard":
    #"octocat":
    #"rage1":
    #"rage2":
    #"rage3":
    #"rage4":
    #"shipit":
    #"squirrel":
    #"suspect":
    #"trollface":
}
